// What the user reads for each failure code the API sends. The API's own
// `error` text is only a fallback for a code this build does not know yet (a
// newer server), so every refusal reads the same wherever the web shows it.

import type { ErrorCode } from '@voice-room/shared/contracts/errors';

const TRY_LATER = 'Слишком много попыток, попробуйте позже';
const UNAVAILABLE = 'Сервис временно недоступен, попробуйте позже';
const VOICE_UNAVAILABLE = 'Голосовая связь временно недоступна';
const IMAGE_FAILED = 'Не удалось загрузить изображение';

export const ERROR_TEXTS: Record<ErrorCode, string> = {
  invalid_request: 'Некорректный запрос',
  authentication_required: 'Требуется вход',
  forbidden: 'Недостаточно прав',
  not_found: 'Не найдено',
  rate_limited: TRY_LATER,
  internal_error: 'Ошибка сервера, попробуйте позже',
  cross_origin_rejected: 'Запрос отклонён: откройте сайт заново',
  not_supported: 'Не поддерживается',
  readiness_unavailable: UNAVAILABLE,

  account_not_found: 'Аккаунт не найден',
  account_deleted: 'Аккаунт удалён',
  account_already_deleted: 'Аккаунт уже удалён',
  account_deletion_pending: 'Аккаунт ожидает удаления',
  account_deletion_unavailable: 'Удаление аккаунта сейчас недоступно',
  invalid_login: 'Логин: 3–32 символа, латиница, цифры, . _ -',
  login_taken: 'Этот логин уже занят',
  password_too_short: 'Пароль должен быть не короче 8 символов',
  passwords_mismatch: 'Пароли не совпадают',
  wrong_password: 'Неверный пароль',
  wrong_current_password: 'Неверный текущий пароль',
  invalid_credentials: 'Неверный логин или пароль',
  invalid_recovery: 'Неверный логин или код восстановления',
  session_not_found: 'Сеанс не найден',
  current_session: 'Чтобы завершить этот сеанс, выйдите из аккаунта',
  login_alert_not_found: 'Вход не найден или на него уже ответили',

  user_not_found: 'Пользователь не найден',
  invalid_user: 'Неверный пользователь',
  cannot_befriend_self: 'Нельзя добавить себя',
  friend_request_refused: 'Заявку отправить нельзя',
  friend_request_not_found: 'Заявка не найдена',
  friend_request_rate_limited: 'Слишком много заявок, попробуйте позже',
  friend_not_found: 'Друг не найден',
  not_friends: 'Вы не друзья',
  relationship_blocked: 'Сообщение недоступно',
  cannot_block_user: 'Нельзя заблокировать этого пользователя',
  block_failed: 'Не удалось сохранить блокировку',
  user_not_blocked: 'Пользователь не заблокирован',

  room_not_found: 'Комната не найдена',
  room_gone: 'Комната больше не существует',
  invalid_room: 'Неверный код комнаты',
  room_name_required: 'Дайте комнате название',
  static_room_requires_login: 'Требуется вход для создания постоянной комнаты',
  room_create_rate_limited: 'Слишком много новых комнат, попробуйте позже',
  room_not_static: 'В список можно добавить только постоянную комнату',
  room_forbidden: 'Комната недоступна',
  room_full: 'Комната заполнена',
  room_banned: 'Вы заблокированы в этой комнате',
  room_owner: 'Владелец не может покинуть свою комнату',
  room_owner_cannot_leave: 'Владелец не может покинуть свою комнату',
  room_leave_failed: 'Не удалось покинуть комнату',
  room_leave_unavailable: 'Не удалось покинуть комнату, попробуйте позже',
  static_room_quota: 'Можно владеть максимум 3 постоянными комнатами',
  temporary_room_quota: 'Слишком много временных комнат, используйте одну из них',
  room_delete_peer_cleanup_failed: 'Не удалось удалить комнату, попробуйте позже',
  room_ban_peer_cleanup_failed: 'Не удалось заблокировать участника, попробуйте позже',
  room_ban_limit: 'Достигнут предел блокировок в комнате',
  owner_required: 'Это может только владелец комнаты',
  peer_not_found: 'Участник не найден',
  cannot_kick_owner: 'Нельзя исключить владельца комнаты',
  cannot_ban_owner: 'Нельзя заблокировать владельца комнаты',
  cannot_mute_owner: 'Нельзя выключить микрофон владельцу комнаты',
  server_mute_unsupported: 'Участник не поддерживает модерацию микрофона',
  server_mute_unavailable: VOICE_UNAVAILABLE,
  ban_not_found: 'Блокировка не найдена',
  invalid_ring_target: 'Этому пользователю нельзя позвонить',
  invite_cooldown: 'Приглашение уже отправлено, подождите немного',
  state_updates_require_websocket: 'Соединение с комнатой потеряно, обновите страницу',
  presence_or_login_required: 'Войдите в комнату или в аккаунт',
  membership_required: 'Сначала вступите в комнату',
  membership_unavailable: UNAVAILABLE,
  membership_persist_failed: UNAVAILABLE,
  credential_revoke_unavailable: UNAVAILABLE,
  pow_required: 'Не удалось создать комнату',
  pow_invalid: 'Не удалось создать комнату',
  pow_expired: 'Проверка создания комнаты истекла',
  pow_reused: 'Не удалось создать комнату',

  invalid_session: 'Сессия участника недействительна',
  not_in_room: 'Сначала нужно войти в комнату',
  livekit_unconfigured: VOICE_UNAVAILABLE,
  livekit_gate_unavailable: VOICE_UNAVAILABLE,
  livekit_gate_principal_unavailable: VOICE_UNAVAILABLE,
  livekit_gate_credential_unavailable: VOICE_UNAVAILABLE,
  livekit_gate_revoke_unavailable: VOICE_UNAVAILABLE,
  livekit_gate_principal_missing: VOICE_UNAVAILABLE,

  message_not_found: 'Сообщение не найдено',
  message_not_visible: 'Сообщение недоступно',
  empty_message: 'Пустое сообщение',
  invalid_message: 'Сообщение не отправлено: неверный формат',
  invalid_message_content: 'Сообщение не отправлено: неверный формат',
  invalid_mentions: 'Не удалось отметить участников',
  invalid_mention_target: 'Этого участника нельзя отметить',
  self_mention: 'Нельзя отметить себя',
  too_many_mentions: 'Слишком много упоминаний в одном сообщении',
  invalid_attachments: 'Вложения недоступны, прикрепите их заново',
  reply_unavailable: 'Сообщение, на которое вы отвечаете, недоступно',
  message_rate_limited: 'Слишком много сообщений, попробуйте позже',
  message_edit_forbidden: 'Можно редактировать только свои сообщения',
  message_delete_forbidden: 'Можно удалять только свои сообщения',
  structured_messages_unavailable: 'Форматированные сообщения сейчас недоступны',
  thread_not_found: 'Диалог не найден',
  thread_forbidden: 'Диалог недоступен',
  invite_not_found: 'Приглашение не найдено',
  invite_not_editable: 'Приглашение нельзя редактировать',
  invite_already_answered: 'Приглашение уже обработано',
  not_invited: 'Отвечать может только приглашённый',
  invalid_action: 'Неверное действие',
  invalid_cursor: 'Не удалось загрузить историю, обновите страницу',
  invalid_read_cursor: 'Не удалось отметить прочитанное',
  history_error: 'Не удалось загрузить историю',
  invalid_conversation: 'Диалог недоступен',
  invalid_reaction: 'Эту реакцию поставить нельзя',
  invalid_reactor_query: 'Некорректный запрос',
  reaction_write_disabled: 'Реакции сейчас недоступны',
  reaction_error: 'Не удалось поставить реакцию',
  account_required: 'Нужен аккаунт',
  pin_limit_reached: 'Достигнут предел закреплённых сообщений',
  pin_error: 'Не удалось закрепить сообщение',

  invalid_notification_target: 'Неверная цель уведомлений',
  temporary_room: 'Отключить уведомления можно только в постоянной комнате',
  not_saved_room: 'Комната не добавлена в список',
  invalid_level: 'Неверный уровень уведомлений',
  push_disabled: 'Push-уведомления отключены на сервере',
  invalid_push_subscription: 'Не удалось включить push-уведомления',
  invalid_push_endpoint: 'Не удалось отключить push-уведомления',
  push_endpoint_conflict: 'Это устройство уже подписано другим аккаунтом',
  push_rate_limited: TRY_LATER,

  media_error: IMAGE_FAILED,
  media_uploads_disabled: 'Загрузка изображений временно недоступна',
  media_attachment_id_invalid: IMAGE_FAILED,
  media_not_found: 'Изображение не найдено',
  media_body_required: IMAGE_FAILED,
  media_byte_quota: 'Закончилось место для изображений',
  media_context_invalid: IMAGE_FAILED,
  media_invalid_image: 'Файл не похож на изображение',
  media_pending_limit: 'Дождитесь загрузки предыдущих изображений',
  media_pixel_limit: 'Изображение слишком большое',
  media_rate_limit: 'Слишком много загрузок, попробуйте позже',
  media_request_id_required: IMAGE_FAILED,
  media_retry_unavailable: 'Повторить загрузку нельзя, прикрепите изображение заново',
  media_size_invalid: IMAGE_FAILED,
  media_size_mismatch: IMAGE_FAILED,
  media_state_conflict: IMAGE_FAILED,
  media_too_large: 'Изображение больше 10 МБ',
  media_type_mismatch: 'Поддерживаются JPEG, PNG и WebP',
  media_type_unsupported: 'Поддерживаются JPEG, PNG и WebP',
  avatar_field_required: 'Выберите изображение',
  avatar_too_large: 'Аватар должен быть не больше 5 МБ',
  upload_rate_limited: 'Слишком много загрузок, попробуйте позже',
  image_not_found: 'Изображение не найдено',

  desktop_release_unavailable: 'Не удалось получить данные о релизе'
};

/** The text for a failure code, or null when this build does not know the code. */
export function errorText(code: string): string | null {
  return Object.hasOwn(ERROR_TEXTS, code) ? ERROR_TEXTS[code as ErrorCode] : null;
}
