function $<T extends Element>(selector: string): T {
  const element = document.querySelector<T>(selector);
  if (!element) throw new Error(`Missing required element: ${selector}`);
  return element;
}

export const elements = {
  brand: $<HTMLAnchorElement>('.brand'),
  copyCodeButton: $<HTMLButtonElement>('#copyCodeButton'),
  copyLinkButton: $<HTMLButtonElement>('#copyLinkButton'),
  createRoomButton: $<HTMLButtonElement>('#createRoomButton'),
  deviceMenuButton: $<HTMLButtonElement>('#deviceMenuButton'),
  devicePopover: $<HTMLElement>('#devicePopover'),
  deviceSelect: $<HTMLSelectElement>('#deviceSelect'),
  emptyRoom: $<HTMLElement>('#emptyRoom'),
  gateThresholdSlider: $<HTMLInputElement>('#gateThresholdSlider'),
  gateThresholdValue: $<HTMLOutputElement>('#gateThresholdValue'),
  joinByCodeButton: $<HTMLButtonElement>('#joinByCodeButton'),
  leaveButton: $<HTMLButtonElement>('#leaveButton'),
  micGateMarker: $<HTMLElement>('#micGateMarker'),
  micLevelFill: $<HTMLElement>('#micLevelFill'),
  micLevelTrack: $<HTMLElement>('#micLevelTrack'),
  muteButton: $<HTMLButtonElement>('#muteButton'),
  muteText: $<HTMLElement>('#muteText'),
  noiseModeSelect: $<HTMLSelectElement>('#noiseModeSelect'),
  notFoundScreen: $<HTMLElement>('#notFoundScreen'),
  outputButton: $<HTMLButtonElement>('#outputButton'),
  outputDeviceSelect: $<HTMLSelectElement>('#outputDeviceSelect'),
  outputMenuButton: $<HTMLButtonElement>('#outputMenuButton'),
  outputPopover: $<HTMLElement>('#outputPopover'),
  outputText: $<HTMLElement>('#outputText'),
  participants: $<HTMLElement>('#participants'),
  roomCodeInput: $<HTMLInputElement>('#roomCodeInput'),
  roomScreen: $<HTMLElement>('#roomScreen'),
  roomTitle: $<HTMLHeadingElement>('#roomTitle'),
  topbarRoomHeading: $<HTMLElement>('.topbar-room-heading'),
  missingRoomCode: $<HTMLElement>('#missingRoomCode'),
  screenButton: $<HTMLButtonElement>('#screenButton'),
  screenExitButton: $<HTMLButtonElement>('#screenExitButton'),
  screenFullscreenButton: $<HTMLButtonElement>('#screenFullscreenButton'),
  screenMeta: $<HTMLElement>('#screenMeta'),
  screenMetaProfile: $<HTMLElement>('#screenMetaProfile'),
  screenMetaStats: $<HTMLElement>('#screenMetaStats'),
  screenMetaTitle: $<HTMLElement>('#screenMetaTitle'),
  screenMetaViewers: $<HTMLElement>('#screenMetaViewers'),
  screenPlaceholder: $<HTMLElement>('#screenPlaceholder'),
  screenSourceCloseButton: $<HTMLButtonElement>('#screenSourceCloseButton'),
  screenSourceDialog: $<HTMLElement>('#screenSourceDialog'),
  screenSourceOptions: $<HTMLElement>('#screenSourceOptions'),
  screenStage: $<HTMLElement>('#screenStage'),
  screenText: $<HTMLElement>('#screenText'),
  screenVideo: $<HTMLVideoElement>('#screenVideo'),
  screenViewControls: $<HTMLElement>('#screenViewControls'),
  soundButton: $<HTMLButtonElement>('#soundButton'),
  stageStripKicker: $<HTMLElement>('#stageStripKicker'),
  stageStripSummary: $<HTMLElement>('#stageStripSummary'),
  startForm: $<HTMLFormElement>('#startForm'),
  startNameInput: $<HTMLInputElement>('#startNameInput'),
  startNameStatus: $<HTMLElement>('#startNameStatus'),
  startScreen: $<HTMLElement>('#startScreen'),
  statusPill: $<HTMLElement>('#statusPill'),
  statusText: $<HTMLElement>('#statusText'),
  tileGrid: $<HTMLElement>('#tileGrid'),
  streamTiles: $<HTMLElement>('#streamTiles'),
  streamVolumeButton: $<HTMLButtonElement>('#streamVolumeButton'),
  streamVolumeSlider: $<HTMLInputElement>('#streamVolumeSlider'),
  stripToggleButton: $<HTMLButtonElement>('#stripToggleButton'),
  template: $<HTMLTemplateElement>('#participantTemplate'),
  toast: $<HTMLElement>('#toast')
};
