// Every code an HTTP failure can carry. The API picks one for each refusal;
// the web shows the user a text it chooses for the code (apps/web
// src/lib/api/error-texts.ts), so wording lives on the client and a code the
// web does not know is a type error there.

export const ERROR_CODES = [
  // Any route
  'invalid_request',
  'authentication_required',
  'forbidden',
  'not_found',
  'rate_limited',
  'internal_error',
  'cross_origin_rejected',
  'not_supported',
  'readiness_unavailable',

  // Account
  'account_not_found',
  'account_deleted',
  'account_already_deleted',
  'account_deletion_pending',
  'account_deletion_unavailable',
  'invalid_login',
  'login_taken',
  'password_too_short',
  'passwords_mismatch',
  'wrong_password',
  'wrong_current_password',
  'invalid_credentials',
  'invalid_recovery',
  'session_not_found',
  'current_session',
  'login_alert_not_found',

  // Friends and blocks
  'user_not_found',
  'invalid_user',
  'cannot_befriend_self',
  'friend_request_refused',
  'friend_request_not_found',
  'friend_request_rate_limited',
  'friend_not_found',
  'not_friends',
  'relationship_blocked',
  'cannot_block_user',
  'block_failed',
  'user_not_blocked',

  // Rooms, membership and moderation
  'room_not_found',
  'room_gone',
  'invalid_room',
  'room_name_required',
  'static_room_requires_login',
  'room_create_rate_limited',
  'room_not_static',
  'room_forbidden',
  'room_full',
  'room_banned',
  'room_owner',
  'room_owner_cannot_leave',
  'room_leave_failed',
  'room_leave_unavailable',
  'static_room_quota',
  'temporary_room_quota',
  'room_delete_peer_cleanup_failed',
  'room_ban_peer_cleanup_failed',
  'room_ban_limit',
  'owner_required',
  'peer_not_found',
  'cannot_kick_owner',
  'cannot_ban_owner',
  'cannot_mute_owner',
  'server_mute_unsupported',
  'server_mute_unavailable',
  'ban_not_found',
  'invalid_ring_target',
  'invite_cooldown',
  'state_updates_require_websocket',
  'presence_or_login_required',
  'membership_required',
  'membership_unavailable',
  'membership_persist_failed',
  'credential_revoke_unavailable',
  'pow_required',
  'pow_invalid',
  'pow_expired',
  'pow_reused',

  // Voice admission
  'invalid_session',
  'not_in_room',
  'livekit_unconfigured',
  'livekit_gate_unavailable',
  'livekit_gate_principal_unavailable',
  'livekit_gate_credential_unavailable',
  'livekit_gate_revoke_unavailable',
  'livekit_gate_principal_missing',

  // Messages, history, reactions and pins
  'message_not_found',
  'message_not_visible',
  'empty_message',
  'invalid_message',
  'invalid_message_content',
  'invalid_mentions',
  'invalid_mention_target',
  'self_mention',
  'too_many_mentions',
  'invalid_attachments',
  'reply_unavailable',
  'message_rate_limited',
  'message_edit_forbidden',
  'message_delete_forbidden',
  'structured_messages_unavailable',
  'thread_not_found',
  'thread_forbidden',
  'invite_not_found',
  'invite_not_editable',
  'invite_already_answered',
  'not_invited',
  'invalid_action',
  'invalid_cursor',
  'invalid_read_cursor',
  'history_error',
  'invalid_conversation',
  'invalid_reaction',
  'invalid_reactor_query',
  'reaction_write_disabled',
  'account_required',
  'pin_limit_reached',
  'pin_error',
  'reaction_error',

  // Notifications and push
  'invalid_notification_target',
  'temporary_room',
  'not_saved_room',
  'invalid_level',
  'push_disabled',
  'invalid_push_subscription',
  'invalid_push_endpoint',
  'push_endpoint_conflict',
  'push_rate_limited',

  // Attachments and avatars
  'media_error',
  'media_uploads_disabled',
  'media_attachment_id_invalid',
  'media_not_found',
  'media_body_required',
  'media_byte_quota',
  'media_context_invalid',
  'media_invalid_image',
  'media_pending_limit',
  'media_pixel_limit',
  'media_rate_limit',
  'media_request_id_required',
  'media_retry_unavailable',
  'media_size_invalid',
  'media_size_mismatch',
  'media_state_conflict',
  'media_too_large',
  'media_type_mismatch',
  'media_type_unsupported',
  'avatar_field_required',
  'avatar_too_large',
  'upload_rate_limited',
  'image_not_found',

  // Desktop app
  'desktop_release_unavailable'
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

const KNOWN = new Set<string>(ERROR_CODES);

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && KNOWN.has(value);
}
