/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type PushSubscriptionPlatformClass = "desktop" | "mobile" | "unknown";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountLoginEvents {
  alert: Generated<boolean>;
  client: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  location_label: Generated<string>;
  os: Generated<string>;
  resolution: string | null;
  resolved_at: Timestamp | null;
  session_public_id: string | null;
  user_id: string;
}

export interface AccountRecoveryCodes {
  code_hash: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface CapabilityRuntimeHeartbeats {
  capability_tokens: Generated<string[]>;
  contract_version: string | null;
  manifest_digest: string | null;
  manifest_schema_version: number | null;
  public_capabilities: Generated<string[]>;
  ready: Generated<boolean>;
  runtime_id: string;
  runtime_kind: string;
  updated_at: Generated<Timestamp>;
}

export interface DirectMessageReactionRevisions {
  emoji: string;
  message_id: string;
  revision: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface DirectMessageReactions {
  created_at: Generated<Timestamp>;
  emoji: string;
  message_id: string;
  revision: Int8;
  user_id: string;
}

export interface DirectMessageReadCursors {
  last_read_message_created_at: Timestamp;
  last_read_message_id: string;
  peer_user_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface DirectMessages {
  body: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  edited_at: Timestamp | null;
  id: string;
  metadata: Generated<Json>;
  read_at: Timestamp | null;
  recipient_id: string;
  reply_to_message_id: string | null;
  sender_id: string;
}

export interface FriendRequests {
  addressee_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  metadata: Generated<Json>;
  requester_id: string;
  responded_at: Timestamp | null;
  status: Generated<string>;
}

export interface Friendships {
  created_at: Generated<Timestamp>;
  id: string;
  metadata: Generated<Json>;
  user_a_id: string;
  user_b_id: string;
}

export interface LinkPreviews {
  expires_at: Timestamp;
  failure_code: string | null;
  fetched_at: Generated<Timestamp>;
  preview: Json | null;
  status: string;
  url: string;
  url_hash: string;
}

export interface LivekitGateCredentials {
  created_at: Generated<Timestamp>;
  credential_hash: string;
  expires_at: Timestamp;
  id: string;
  metadata: Generated<Json>;
  peer_id: string;
  principal_epoch: number;
  principal_id: string;
  principal_type: string;
  revoked_at: Timestamp | null;
  room_id: string;
}

export interface LivekitGatePrincipalEpochs {
  epoch: Generated<number>;
  principal_id: string;
  principal_type: string;
  room_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MediaProcessingJobs {
  attachment_id: string;
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  claimed_at: Timestamp | null;
  claimed_by: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  dead_at: Timestamp | null;
  fencing_token: Generated<Int8>;
  id: string;
  kind: Generated<string>;
  last_error: string | null;
  lease_expires_at: Timestamp | null;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface MessageAttachments {
  attachment_order: number | null;
  bound_at: Timestamp | null;
  client_request_id: string | null;
  context: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  direct_message_id: string | null;
  failed_at: Timestamp | null;
  failure_code: string | null;
  height: number | null;
  id: string;
  metadata: Generated<Json>;
  mime_type: string | null;
  original_bytes: Int8 | null;
  original_storage_key: string | null;
  owner_id: string;
  preview_bytes: Int8 | null;
  preview_storage_key: string | null;
  processed_bytes: Int8 | null;
  processed_storage_key: string | null;
  ready_at: Timestamp | null;
  reservation_expires_at: Timestamp | null;
  reserved_bytes: Int8 | null;
  room_message_id: string | null;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
  uploaded_at: Timestamp | null;
  width: number | null;
}

export interface MessageDeliveryLeases {
  expires_at: Generated<Timestamp>;
  fencing_token: Generated<Int8>;
  heartbeat_at: Timestamp | null;
  identity: string;
  owner_id: string | null;
  ready: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface MessageDeliveryOutbox {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  claimed_at: Timestamp | null;
  claimed_fencing_token: Int8 | null;
  conversation_id: string;
  conversation_type: string;
  created_at: Generated<Timestamp>;
  dead_at: Timestamp | null;
  delivered_at: Timestamp | null;
  event_id: string;
  event_type: string;
  last_error: string | null;
  logical_key: string;
  message_id: string;
  payload: Json;
  revision: Generated<Int8>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface MessageSendIdempotency {
  actor_id: string;
  actor_type: string;
  completed_at: Timestamp | null;
  conversation_id: string;
  conversation_type: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  fingerprint: string;
  idempotency_key: string;
  ledger_key: string;
  message_id: string | null;
  response_body: Json | null;
  response_status: number | null;
  state: Generated<string>;
}

export interface NotificationDeliveryLeases {
  expires_at: Generated<Timestamp>;
  fencing_token: Generated<Int8>;
  heartbeat_at: Timestamp | null;
  identity: string;
  owner_id: string | null;
  ready: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface NotificationDmMutes {
  created_at: Generated<Timestamp>;
  id: string;
  metadata: Generated<Json>;
  peer_user_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface NotificationOutbox {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  channel: Generated<string>;
  claimed_at: Timestamp | null;
  claimed_fencing_token: Int8 | null;
  created_at: Generated<Timestamp>;
  dead_at: Timestamp | null;
  delivered_at: Timestamp | null;
  event_id: string;
  last_error: string | null;
  notification_id: string;
  payload: Json;
  recipient_user_id: string;
  revision: Int8;
  status: Generated<string>;
  suppressed_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface NotificationPreferences {
  created_at: Generated<Timestamp>;
  metadata: Generated<Json>;
  private_notifications: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface NotificationRoomMutes {
  created_at: Generated<Timestamp>;
  id: string;
  level: Generated<string>;
  metadata: Generated<Json>;
  room_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PushSubscriptions {
  auth: string;
  created_at: Generated<Timestamp>;
  endpoint: string;
  id: string;
  last_success_at: Timestamp | null;
  metadata: Generated<Json>;
  p256dh: string;
  platform_class: Generated<PushSubscriptionPlatformClass>;
  user_id: string;
}

export interface ReservedLogins {
  login_hash: string;
  reserved_at: Generated<Timestamp>;
}

export interface RoomBans {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: string;
  idempotency_key: string | null;
  ip: Generated<string>;
  metadata: Generated<Json>;
  reason: Generated<string>;
  revoked_at: Timestamp | null;
  room_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface RoomBookmarks {
  created_at: Generated<Timestamp>;
  id: string;
  metadata: Generated<Json>;
  room_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface RoomChatReads {
  last_read_at: Timestamp;
  last_read_message_created_at: Timestamp | null;
  last_read_message_id: string | null;
  room_id: string;
  user_id: string;
}

export interface RoomMemberships {
  created_at: Generated<Timestamp>;
  id: string;
  metadata: Generated<Json>;
  role: Generated<string>;
  room_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface RoomMessageMentions {
  created_at: Generated<Timestamp>;
  creator_user_id: string;
  id: string;
  message_id: string;
  retracted_at: Timestamp | null;
  revision: Generated<Int8>;
  room_id: string;
  target_user_id: string;
}

export interface RoomMessagePins {
  message_id: string;
  pinned_at: Generated<Timestamp>;
  pinned_by: string;
  room_id: string;
}

export interface RoomMessageReactionRevisions {
  emoji: string;
  message_id: string;
  revision: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface RoomMessageReactions {
  created_at: Generated<Timestamp>;
  emoji: string;
  message_id: string;
  revision: Int8;
  user_id: string;
}

export interface RoomMessages {
  author_user_id: string | null;
  content: Json | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  edited_at: Timestamp | null;
  expires_at: Timestamp | null;
  id: string;
  metadata: Generated<Json>;
  name: Generated<string>;
  peer_id: Generated<string>;
  reply_to_message_id: string | null;
  room_id: string;
  text: string;
}

export interface RoomPeerIdentities {
  avatar_color_key: string;
  created_at: Generated<Timestamp>;
  display_name: Generated<string>;
  id: string;
  last_seen_at: Generated<Timestamp>;
  metadata: Generated<Json>;
  peer_id: string;
  room_id: string;
  session_token_hash: string;
}

export interface Rooms {
  avatar_key: string | null;
  created_at: Generated<Timestamp>;
  creator_ip: Generated<string>;
  deleted_at: Timestamp | null;
  emoji: Generated<string>;
  empty_since: Timestamp | null;
  id: string;
  is_static: Generated<boolean>;
  metadata: Generated<Json>;
  name: Generated<string>;
  owner_id: string | null;
  room_color_key: Generated<string>;
  room_icon_key: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface RoomServerMutes {
  created_at: Generated<Timestamp>;
  muted_by: string;
  principal_id: string;
  principal_type: string;
  room_id: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  last_seen_at: Generated<Timestamp>;
  location_label: Generated<string>;
  public_id: Generated<string>;
  user_agent: Generated<string>;
  user_id: string;
}

export interface UserBlocks {
  blocked_id: string;
  blocker_id: string;
  created_at: Generated<Timestamp>;
}

export interface UserNotifications {
  actor_user_id: string;
  body: Generated<string>;
  created_at: Generated<Timestamp>;
  id: string;
  read_at: Timestamp | null;
  reasons: string[];
  recipient_user_id: string;
  retracted_at: Timestamp | null;
  revision: Generated<Int8>;
  room_id: string;
  source_message_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  avatar_accent: string | null;
  avatar_color_key: Generated<string>;
  avatar_key: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  deletion_requested_at: Timestamp | null;
  display_name: Generated<string>;
  dnd: Generated<boolean>;
  id: string;
  login: string;
  metadata: Generated<Json>;
  password_hash: string;
  presence_active_until: Timestamp | null;
  presence_status: Generated<string>;
  presence_status_automatic: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  account_login_events: AccountLoginEvents;
  account_recovery_codes: AccountRecoveryCodes;
  capability_runtime_heartbeats: CapabilityRuntimeHeartbeats;
  direct_message_reaction_revisions: DirectMessageReactionRevisions;
  direct_message_reactions: DirectMessageReactions;
  direct_message_read_cursors: DirectMessageReadCursors;
  direct_messages: DirectMessages;
  friend_requests: FriendRequests;
  friendships: Friendships;
  link_previews: LinkPreviews;
  livekit_gate_credentials: LivekitGateCredentials;
  livekit_gate_principal_epochs: LivekitGatePrincipalEpochs;
  media_processing_jobs: MediaProcessingJobs;
  message_attachments: MessageAttachments;
  message_delivery_leases: MessageDeliveryLeases;
  message_delivery_outbox: MessageDeliveryOutbox;
  message_send_idempotency: MessageSendIdempotency;
  notification_delivery_leases: NotificationDeliveryLeases;
  notification_dm_mutes: NotificationDmMutes;
  notification_outbox: NotificationOutbox;
  notification_preferences: NotificationPreferences;
  notification_room_mutes: NotificationRoomMutes;
  push_subscriptions: PushSubscriptions;
  reserved_logins: ReservedLogins;
  room_bans: RoomBans;
  room_bookmarks: RoomBookmarks;
  room_chat_reads: RoomChatReads;
  room_memberships: RoomMemberships;
  room_message_mentions: RoomMessageMentions;
  room_message_pins: RoomMessagePins;
  room_message_reaction_revisions: RoomMessageReactionRevisions;
  room_message_reactions: RoomMessageReactions;
  room_messages: RoomMessages;
  room_peer_identities: RoomPeerIdentities;
  room_server_mutes: RoomServerMutes;
  rooms: Rooms;
  sessions: Sessions;
  user_blocks: UserBlocks;
  user_notifications: UserNotifications;
  users: Users;
}
